# Generated by Django 6.0.3 on 2026-03-11 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApllication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.IntegerField(default=1000)),
                ('terms', models.IntegerField(help_text='Loan term in days')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('education', models.CharField(choices=[('High School or Below', 'High School or Below'), ('Bechalor', 'Bachelor'), ('college', 'College'), ('Master or Above', 'Master or Above')], max_length=50)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('prediction_result', models.CharField(blank=True, max_length=20, null=True)),
                ('probability_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
