# Generated by Django 6.0.2 on 2026-03-11 04:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanApllication',
            new_name='LoanApplication',
        ),
    ]
